from datetime import datetime, timedelta

# 현재 날짜 기준으로 유효한 날짜 생성
current_date = datetime.now()
start_date = current_date.strftime('%Y-%m-%d')
end_date_1month = (current_date + timedelta(days=30)).strftime('%Y-%m-%d')
end_date_3months = (current_date + timedelta(days=90)).strftime('%Y-%m-%d') 
end_date_6months = (current_date + timedelta(days=180)).strftime('%Y-%m-%d')
end_date_1year = (current_date + timedelta(days=365)).strftime('%Y-%m-%d')

print(f"현재 날짜: {current_date.strftime('%Y년 %m월 %d일')}")
print(f"업데이트된 날짜 범위: {start_date} ~ {end_date_6months}")

MULTI_CATEGORY_DATA = [
    # ==================== 카페 | 스타벅스 ====================
    {
        "id": "stbx-202508-ima-lecture",
        "brand": "스타벅스",
        "brand_aliases": ["Starbucks","스타벅스코리아","스벅","스타벅스 앱"],
        "category": "카페",
        "title": "이마트 여름학기 컬쳐클럽",
        "benefit_type": "기타",
        "discount_rate": 0.0,
        "conditions": "이마트 문화센터 커피 클래스",
        "valid_from": "2025-08-11",
        "valid_to": "2025-08-31",
        "source_url": "https://www.starbucks.co.kr/whats_new/campaign_list.do",
        "is_active": True,
        "text": "[카페/스타벅스] 이마트에서 진행하는 커피 클래스 이벤트."
    },
    {
        "id": "stbx-202508-starry",
        "brand": "스타벅스",
        "brand_aliases": ["Starbucks","스벅"],
        "category": "카페",
        "title": "STARRY ★ COME BACK!",
        "benefit_type": "적립",
        "discount_rate": 0.0,
        "conditions": "인기 음료 구매 시 별 3개 추가 적립",
        "valid_from": "2025-08-11",
        "valid_to": "2025-08-14",
        "source_url": "https://www.starbucks.co.kr/whats_new/campaign_list.do",
        "is_active": True,
        "text": "[카페/스타벅스] 인기 음료 구매 시 별 추가 적립 프로모션."
    },
    {
        "id": "stbx-202508-twice-joy",
        "brand": "스타벅스",
        "brand_aliases": ["Starbucks","스벅"],
        "category": "카페",
        "title": "TWICE THE JOY",
        "benefit_type": "쿠폰",
        "discount_rate": 0.0,
        "conditions": "보유 별 6개 → 프라푸치노/블렌디드 1+1 쿠폰 교환",
        "valid_from": "2025-08-11",
        "valid_to": "2025-08-14",
        "source_url": "https://www.starbucks.co.kr/whats_new/campaign_list.do",
        "is_active": True,
        "text": "[카페/스타벅스] 별 6개로 1+1 쿠폰 교환 후 사용."
    },
    {
        "id": "stbx-202508-star-summer",
        "brand": "스타벅스",
        "brand_aliases": ["Starbucks","스벅","현대카드"],
        "category": "카페",
        "title": "STAR SUMMER",
        "benefit_type": "복합",
        "discount_rate": 0.0,
        "conditions": "스타벅스 현대카드 특정 조건 충족",
        "valid_from": "2025-08-08",
        "valid_to": "2025-08-31",
        "source_url": "https://www.starbucks.co.kr/whats_new/campaign_list.do",
        "is_active": True,
        "text": "사이렌 스태킹 머그 세트·별 100개·Buddy Pass 1개월 구독료 캐시백 등 제공."
    },
    {
        "id": "stbx-202508-kb-easy-account",
        "brand": "스타벅스",
        "brand_aliases": ["Starbucks","스벅","KB국민"],
        "category": "카페",
        "title": "계좌 간편결제 기본 결제수단 지정 이벤트",
        "benefit_type": "적립",
        "discount_rate": 0.0,
        "conditions": "KB계좌 최초 연동·결제",
        "valid_from": "2025-08-05",
        "valid_to": "2025-08-18",
        "source_url": "https://www.starbucks.co.kr/whats_new/campaign_list.do",
        "is_active": True,
        "text": "추가 별 적립 + 톨 아메리카노 쿠폰 제공."
    },
    {
        "id": "stbx-202508-giftcard",
        "brand": "스타벅스",
        "brand_aliases": ["Starbucks","스벅"],
        "category": "카페",
        "title": "모바일 상품권/모바일 카드 선물 이벤트",
        "benefit_type": "기타",
        "discount_rate": 0.0,
        "conditions": "모바일 카드 구매/선물",
        "valid_from": "2025-08-01",
        "valid_to": "2025-08-29",
        "source_url": "https://www.starbucks.co.kr/whats_new/campaign_list.do",
        "is_active": True,
        "text": "모바일 카드 구매·선물 시 혜택 제공."
    },
    {
        "id": "stbx-202508-hyundai-aug",
        "brand": "스타벅스",
        "brand_aliases": ["Starbucks","현대카드","스벅"],
        "category": "카페",
        "title": "스타벅스 현대카드 8월 혜택",
        "benefit_type": "복합",
        "discount_rate": 0.0,
        "conditions": "스타벅스 현대카드 이용",
        "valid_from": "2025-08-01",
        "valid_to": "2025-08-31",
        "source_url": "https://www.starbucks.co.kr/whats_new/campaign_list.do",
        "is_active": True,
        "text": "머그 세트·별 100개 등 최대 9만 원 상당 혜택."
    },
    {
        "id": "stbx-202507-tasty-journey",
        "brand": "스타벅스",
        "brand_aliases": ["Starbucks","스벅"],
        "category": "카페",
        "title": "TASTY JOURNEY",
        "benefit_type": "적립",
        "discount_rate": 0.0,
        "conditions": "제조 음료+케이크 함께 구매",
        "valid_from": "2025-07-21",
        "valid_to": "2025-08-20",
        "source_url": "https://www.starbucks.co.kr/whats_new/campaign_list.do",
        "is_active": True,
        "text": "동시 구매 시 추가 별 증정."
    },
    {
        "id": "stbx-202507-f30-weekend",
        "brand": "스타벅스",
        "brand_aliases": ["Starbucks","스벅"],
        "category": "카페",
        "title": "프라푸치노 30 WEEKEND",
        "benefit_type": "할인",
        "discount_rate": 30.0,
        "conditions": "매주 금·토·일 14~17시, 프라푸치노/블렌디드",
        "valid_from": "2025-07-25",
        "valid_to": "2025-08-17",
        "source_url": "https://www.starbucks.co.kr/whats_new/campaign_list.do",
        "is_active": True,
        "text": "30주년 기념 주말 30% 할인."
    },
    {
        "id": "stbx-202507-ssgpay",
        "brand": "스타벅스",
        "brand_aliases": ["Starbucks","SSGPAY","스벅"],
        "category": "카페",
        "title": "SSGPAY 결제 이벤트",
        "benefit_type": "적립",
        "discount_rate": 5.0,
        "conditions": "SSG머니 충전 결제 첫 이용, 최대 1만원 적립",
        "valid_from": "2025-07-11",
        "valid_to": "2025-08-31",
        "source_url": "https://www.starbucks.co.kr/whats_new/campaign_list.do",
        "is_active": True,
        "text": "결제금액의 5% SSG머니 적립(상한 1만원)."
    },
    {
        "id": "stbx-202507-dt-rain",
        "brand": "스타벅스",
        "brand_aliases": ["Starbucks","스벅","DT"],
        "category": "카페",
        "title": "DT 레인 쿠폰",
        "benefit_type": "할인",
        "discount_rate": 30.0,
        "conditions": "18시 이후 제조 음료",
        "valid_from": "2025-07-04",
        "valid_to": "2025-09-30",
        "source_url": "https://www.starbucks.co.kr/whats_new/campaign_list.do",
        "is_active": True,
        "text": "저녁 6시 이후 30% 할인."
    },
    {
        "id": "stbx-202506-goodevening",
        "brand": "스타벅스",
        "brand_aliases": ["Starbucks","스벅"],
        "category": "카페",
        "title": "굿이브닝",
        "benefit_type": "할인",
        "discount_rate": 30.0,
        "conditions": "18시 이후 샌드위치/케이크와 제조 음료 동시 주문",
        "valid_from": "2025-06-18",
        "valid_to": "2025-09-30",
        "source_url": "https://www.starbucks.co.kr/whats_new/campaign_list.do",
        "is_active": True,
        "text": "동시 주문 시 음료 30% 할인."
    },
    {
        "id": "stbx-202506-reserve-rewards",
        "brand": "스타벅스",
        "brand_aliases": ["Starbucks","리저브"],
        "category": "카페",
        "title": "리저브 리워드 혜택",
        "benefit_type": "적립",
        "discount_rate": 0.0,
        "conditions": "리워드 별 적립",
        "valid_from": "2025-06-17",
        "valid_to": "2025-08-16",
        "source_url": "https://www.starbucks.co.kr/whats_new/campaign_list.do",
        "is_active": True,
        "text": "별 교환으로 무료 제조음료·사이즈업 등."
    },
    {
        "id": "stbx-202505-autocharge",
        "brand": "스타벅스",
        "brand_aliases": ["Starbucks","현대카드"],
        "category": "카페",
        "title": "계좌 간편결제 자동충전",
        "benefit_type": "할인",
        "discount_rate": 0.0,
        "conditions": "현대카드 생활요금 정기결제 신청 + 스타벅스 카드 자동충전 등록",
        "valid_from": "2025-05-27",
        "valid_to": "2025-08-25",
        "source_url": "https://www.starbucks.co.kr/whats_new/campaign_list.do",
        "is_active": True,
        "text": "정기결제·자동충전 결합 할인."
    },
    {
        "id": "stbx-202504-incar-hyundai",
        "brand": "스타벅스",
        "brand_aliases": ["Starbucks","현대차","기아","제네시스"],
        "category": "카페",
        "title": "인카페이먼트 현대카드 별적립",
        "benefit_type": "적립",
        "discount_rate": 0.0,
        "conditions": "차량 인카페이먼트 + 현대카드 결제",
        "valid_from": "2025-04-02",
        "valid_to": "2025-12-31",
        "source_url": "https://www.starbucks.co.kr/whats_new/campaign_list.do",
        "is_active": True,
        "text": "차량 내 주문·결제 시 별 추가 적립."
    },
    {
        "id": "stbx-202412-kt-membership",
        "brand": "스타벅스",
        "brand_aliases": ["Starbucks","KT 멤버십"],
        "category": "카페",
        "title": "KT멤버십 혜택 안내",
        "benefit_type": "할인",
        "discount_rate": 0.0,
        "conditions": "VVIP/VIP 등급 월 1회 아메리카노 숏 무료 또는 4,000원 할인",
        "valid_from": "2024-12-31",
        "valid_to": "2025-12-31",
        "source_url": "https://www.starbucks.co.kr/whats_new/campaign_list.do",
        "is_active": True,
        "text": "KT 멤버십 등급별 월 1회 혜택."
    },

    # ==================== 카페 | 투썸 ====================
    {
        "id": "twosome-202508-cakeweek",
        "brand": "투썸플레이스",
        "brand_aliases": ["투썸","Twosome"],
        "category": "카페",
        "title": "썸머 케이크 위크",
        "benefit_type": "할인",
        "discount_rate": 20.0,
        "conditions": "케이크 구매 시 할인쿠폰",
        "valid_from": "2025-08-07",
        "valid_to": "2025-08-20",
        "source_url": "https://mo.twosome.co.kr/ev/eventList.do",
        "is_active": True,
        "text": "모든 케이크 대상 20% 할인 쿠폰 제공."
    },
    {
        "id": "twosome-202508-disney-cake",
        "brand": "투썸플레이스",
        "brand_aliases": ["투썸","Twosome"],
        "category": "카페",
        "title": "디즈니 케이크 할인",
        "benefit_type": "할인",
        "discount_rate": 0.0,
        "conditions": "투썸하트 정회원 대상",
        "valid_from": "2025-08-05",
        "valid_to": "2025-08-17",
        "source_url": "https://mo.twosome.co.kr/ev/eventList.do",
        "is_active": True,
        "text": "정회원 전용 디즈니 케이크 할인 쿠폰."
    },
    {
        "id": "twosome-202508-hyundai-mpoint70",
        "brand": "투썸플레이스",
        "brand_aliases": ["투썸","현대카드"],
        "category": "카페",
        "title": "현대카드 M포인트 70% 사용",
        "benefit_type": "포인트사용",
        "discount_rate": 70.0,
        "conditions": "현대카드 결제 시 M포인트 차감",
        "valid_from": "2025-08-01",
        "valid_to": "2025-09-30",
        "source_url": "https://mo.twosome.co.kr/ev/eventList.do",
        "is_active": True,
        "text": "결제금액의 70%까지 포인트 사용 가능."
    },
    {
        "id": "twosome-202508-samsung-linkplus",
        "brand": "투썸플레이스",
        "brand_aliases": ["투썸","삼성카드"],
        "category": "카페",
        "title": "8월 삼성 LINK PLUS",
        "benefit_type": "할인",
        "discount_rate": 0.0,
        "conditions": "삼성카드 앱에서 혜택 링크",
        "valid_from": "2025-08-01",
        "valid_to": "2025-08-31",
        "source_url": "https://mo.twosome.co.kr/ev/eventList.do",
        "is_active": True,
        "text": "앱에서 링크 시 카드 할인 제공."
    },
    {
        "id": "twosome-202508-sktvip-pick",
        "brand": "투썸플레이스",
        "brand_aliases": ["투썸","SKT"],
        "category": "카페",
        "title": "SKT VIP PICK",
        "benefit_type": "쿠폰",
        "discount_rate": 0.0,
        "conditions": "SKT VIP 고객 대상 5,000원 쿠폰",
        "valid_from": "2025-08-01",
        "valid_to": "2025-08-31",
        "source_url": "https://mo.twosome.co.kr/ev/eventList.do",
        "is_active": True,
        "text": "VIP 고객 전용 5천원 할인 쿠폰."
    },
    {
        "id": "twosome-202507-matcha-stamp",
        "brand": "투썸플레이스",
        "brand_aliases": ["투썸"],
        "category": "카페",
        "title": "말차 스탬프",
        "benefit_type": "적립",
        "discount_rate": 0.0,
        "conditions": "말차 음료 구매·스탬프 적립",
        "valid_from": "2025-07-28",
        "valid_to": "2025-08-26",
        "source_url": "https://mo.twosome.co.kr/ev/eventList.do",
        "is_active": True,
        "text": "스탬프 모으면 무료 쿠폰 제공."
    },
    {
        "id": "twosome-202506-payco-1pct",
        "brand": "투썸플레이스",
        "brand_aliases": ["투썸","PAYCO"],
        "category": "카페",
        "title": "PAYCO 포인트 적립",
        "benefit_type": "적립",
        "discount_rate": 1.0,
        "conditions": "PAYCO 결제 시 1% 적립",
        "valid_from": "2025-06-01",
        "valid_to": "2025-08-31",
        "source_url": "https://mo.twosome.co.kr/ev/eventList.do",
        "is_active": True,
        "text": "페이코 결제 금액의 1% 적립."
    },
    {
        "id": "twosome-202506-hyundai-goodfriend",
        "brand": "투썸플레이스",
        "brand_aliases": ["투썸","현대카드"],
        "category": "카페",
        "title": "현대카드 GOOD FRIENDSHIP",
        "benefit_type": "할인",
        "discount_rate": 30.0,
        "conditions": "현대카드 2만원 이상 결제",
        "valid_from": "2025-06-01",
        "valid_to": "2025-09-30",
        "source_url": "https://mo.twosome.co.kr/ev/eventList.do",
        "is_active": True,
        "text": "결제금액 30% 할인."
    },
    {
        "id": "twosome-202504-tpass-12000",
        "brand": "투썸플레이스",
        "brand_aliases": ["투썸","T우주"],
        "category": "카페",
        "title": "T우주패스 최대 12,000원 혜택",
        "benefit_type": "할인",
        "discount_rate": 30.0,
        "conditions": "T우주패스 가입 고객",
        "valid_from": "2025-04-23",
        "valid_to": "2025-08-31",
        "source_url": "https://mo.twosome.co.kr/ev/eventList.do",
        "is_active": True,
        "text": "T우주패스 고객 30% 할인(최대 1.2만원)."
    },
    {
        "id": "twosome-202503-skt-club-t",
        "brand": "투썸플레이스",
        "brand_aliases": ["투썸","SKT"],
        "category": "카페",
        "title": "SKT 클럽 T 로밍 프로모션",
        "benefit_type": "할인",
        "discount_rate": 0.0,
        "conditions": "T멤버십 제휴 할인",
        "valid_from": "2025-03-01",
        "valid_to": "2025-12-31",
        "source_url": "https://mo.twosome.co.kr/ev/eventList.do",
        "is_active": True,
        "text": "롯데 제휴 할인 제공."
    },
    {
        "id": "twosome-202501-app-tpass-mpoint",
        "brand": "투썸플레이스",
        "brand_aliases": ["투썸","현대카드","T우주"],
        "category": "카페",
        "title": "T우주·M포인트 앱 결제 적용",
        "benefit_type": "할인",
        "discount_rate": 0.0,
        "conditions": "앱 결제 시 T우주 할인·M포인트 사용 가능",
        "valid_from": "2025-01-15",
        "valid_to": "2025-12-31",
        "source_url": "https://mo.twosome.co.kr/ev/eventList.do",
        "is_active": True,
        "text": "앱 결제에도 동일 혜택 적용."
    },

    # ==================== 카페 | 메가커피/할리스/파스쿠찌/이디야 ====================
    {
        "id": "mega-202508-payco-point",
        "brand": "메가커피",
        "brand_aliases": ["메가MGC커피","MEGA MGC"],
        "category": "카페",
        "title": "페이코 적립 이벤트",
        "benefit_type": "적립",
        "discount_rate": 0.0,
        "conditions": "간편결제 5천원/1만원 이상 시 500P/1500P",
        "valid_from": "2025-08-01",
        "valid_to": "2025-08-24",
        "source_url": "https://www.mega-mgccoffee.com/bbs/?bbs_category=3",
        "is_active": True,
        "text": "금액 구간별 PAYCO 포인트 적립."
    },
    {
        "id": "mega-202508-danggeun-500won",
        "brand": "메가커피",
        "brand_aliases": ["메가MGC커피"],
        "category": "카페",
        "title": "당근페이 할인 EVENT",
        "benefit_type": "할인",
        "discount_rate": 0.0,
        "conditions": "당근페이 5천원 이상 결제 시 500원 할인",
        "valid_from": "2025-08-01",
        "valid_to": "2025-08-31",
        "source_url": "https://www.mega-mgccoffee.com/bbs/?bbs_category=3",
        "is_active": True,
        "text": "결제 즉시 500원 할인 쿠폰."
    },
    {
        "id": "mega-202508-shinhan-sol-500p",
        "brand": "메가커피",
        "brand_aliases": ["메가MGC커피","신한 SOL페이"],
        "category": "카페",
        "title": "신한 SOL페이 적립",
        "benefit_type": "적립",
        "discount_rate": 0.0,
        "conditions": "1천원 이상 결제, 1인 1회",
        "valid_from": "2025-08-01",
        "valid_to": "2025-08-31",
        "source_url": "https://www.mega-mgccoffee.com/bbs/?bbs_category=3",
        "is_active": True,
        "text": "마이신한포인트 500P 적립."
    },
    {
        "id": "hollys-202507-welcome-50",
        "brand": "할리스",
        "brand_aliases": ["Hollys"],
        "category": "카페",
        "title": "WELCOME HOLLYS! 신규 50% 할인",
        "benefit_type": "할인",
        "discount_rate": 50.0,
        "conditions": "신규 가입 시 베스트 5종",
        "valid_from": "2025-07-23",
        "valid_to": "2025-08-31",
        "source_url": "https://www.hollys.co.kr/news/event/list.do?ageNo=1&closeYn=&division=03",
        "is_active": True,
        "text": "베스트 음료 5종 50% 할인 쿠폰 제공."
    },
    {
        "id": "hollys-202505-kakaopay-redday",
        "brand": "할리스",
        "brand_aliases": ["Hollys","카카오페이"],
        "category": "카페",
        "title": "카카오페이 레드데이 선착순 2천원",
        "benefit_type": "할인",
        "discount_rate": 0.0,
        "conditions": "행사일 선착순, 카카오페이 결제",
        "valid_from": "2025-05-28",
        "valid_to": "2025-12-31",
        "source_url": "https://www.hollys.co.kr/news/event/list.do?ageNo=1&closeYn=&division=03",
        "is_active": True,
        "text": "선착순 2,000원 즉시 할인."
    },
    {
        "id": "pascucci-202508-hana-pick",
        "brand": "파스쿠찌",
        "brand_aliases": ["Pascucci","파스쿠치"],
        "category": "카페",
        "title": "[하나카드] 8월 하나Pick",
        "benefit_type": "할인",
        "discount_rate": 0.0,
        "conditions": "1만원 이상 구매 시 2,500원 할인",
        "valid_from": "2025-08-04",
        "valid_to": "2025-08-17",
        "source_url": "https://www.pascucci.co.kr/event/eventList.asp",
        "is_active": True,
        "text": "하나카드 결제 조건 충족 시 즉시할인."
    },
    {
        "id": "pascucci-202508-happyapp-5plus1",
        "brand": "파스쿠찌",
        "brand_aliases": ["Pascucci","해피앱"],
        "category": "카페",
        "title": "[해피앱] 음료 5+1 스탬프",
        "benefit_type": "적립",
        "discount_rate": 0.0,
        "conditions": "제조음료 6잔 중 1잔 무료(스탬프)",
        "valid_from": "2025-08-01",
        "valid_to": "2025-08-31",
        "source_url": "https://www.pascucci.co.kr/event/eventList.asp",
        "is_active": True,
        "text": "5잔 적립 시 1잔 무료."
    },
    {
        "id": "pascucci-202508-happyorder-bingsu20",
        "brand": "파스쿠찌",
        "brand_aliases": ["Pascucci","해피오더"],
        "category": "카페",
        "title": "[해피오더] 그라니따&빙수 20% 혜택",
        "benefit_type": "할인",
        "discount_rate": 20.0,
        "conditions": "쿠폰 적용 시",
        "valid_from": "2025-08-01",
        "valid_to": "2025-08-31",
        "source_url": "https://www.pascucci.co.kr/event/eventList.asp",
        "is_active": True,
        "text": "그라니따/빙수 20% 할인."
    },
    {
        "id": "pascucci-202508-samsunglink-3000",
        "brand": "파스쿠찌",
        "brand_aliases": ["Pascucci","삼성카드 LINK"],
        "category": "카페",
        "title": "[삼성카드 LINK] 8월 특별 혜택",
        "benefit_type": "할인",
        "discount_rate": 0.0,
        "conditions": "1.5만원 이상 결제 시 3,000원 혜택",
        "valid_from": "2025-08-01",
        "valid_to": "2025-08-31",
        "source_url": "https://www.pascucci.co.kr/event/eventList.asp",
        "is_active": True,
        "text": "결제 조건 충족 시 청구할인."
    },
    {
        "id": "ediya-202508-pickup-50",
        "brand": "이디야",
        "brand_aliases": ["EDIYA COFFEE","이디야커피"],
        "category": "카페",
        "title": "멤버스 픽업 주문 50% 즉시할인",
        "benefit_type": "할인",
        "discount_rate": 50.0,
        "conditions": "매일 12시 이후 선착순, 앱 픽업 주문",
        "valid_from": "2025-08-01",
        "valid_to": "2025-08-31",
        "source_url": "https://www.ediya.com/contents/event.html?tb_name=event",
        "is_active": True,
        "text": "선착순 반값 할인."
    },
    {
        "id": "ediya-202404-monday-2000",
        "brand": "이디야",
        "brand_aliases": ["EDIYA COFFEE"],
        "category": "카페",
        "title": "월요일마다 최대 2천원 할인",
        "benefit_type": "할인",
        "discount_rate": 0.0,
        "conditions": "매주 월요일, 조건 충족 시 최대 2,000원",
        "valid_from": "2025-04-07",
        "valid_to": "2025-12-29",
        "source_url": "https://www.ediya.com/contents/event.html?tb_name=event",
        "is_active": True,
        "text": "주간 요일 특가."
    },
    {
        "id": "ediya-202409-hyundai-mpoint20",
        "brand": "이디야",
        "brand_aliases": ["EDIYA COFFEE","현대카드"],
        "category": "카페",
        "title": "현대카드 M포인트 20% 사용",
        "benefit_type": "포인트사용",
        "discount_rate": 20.0,
        "conditions": "현대카드 보유, M포인트 차감",
        "valid_from": "2024-09-01",
        "valid_to": "2025-08-31",
        "source_url": "https://www.ediya.com/contents/event.html?tb_name=event",
        "is_active": True,
        "text": "결제금액 20%를 포인트로 사용."
    },

    # ==================== 편의점 ====================
    {
        "id": "gs25-202508-gspay-first",
        "brand": "GS25",
        "brand_aliases": ["gs25","GS 편의점"],
        "category": "편의점",
        "title": "GS Pay 첫 결제 고객 페이백",
        "benefit_type": "적립",
        "discount_rate": 0.0,
        "conditions": "GS Pay 5,000원 이상 첫 결제, 2,000P 페이백",
        "valid_from": "2025-08-01",
        "valid_to": "2025-08-31",
        "source_url": "http://gs25.gsretail.com/customer-engagement/event/current-events?uiel=Mobile",
        "is_active": True,
        "text": "첫 결제 시 2천 포인트 적립."
    },
    {
        "id": "gs25-202508-bakery-choco-1plus1",
        "brand": "GS25",
        "brand_aliases": ["gs25"],
        "category": "편의점",
        "title": "베이커리·초콜릿 1+1",
        "benefit_type": "증정",
        "discount_rate": 0.0,
        "conditions": "브레디크 15종·페레로 5종",
        "valid_from": "2025-08-01",
        "valid_to": "2025-08-31",
        "source_url": "http://gs25.gsretail.com/customer-engagement/event/current-events?uiel=Mobile",
        "is_active": True,
        "text": "지정 상품 1+1 행사."
    },
    {
        "id": "seven-202508-npay-weekend",
        "brand": "세븐일레븐",
        "brand_aliases": ["7-Eleven","세븐"],
        "category": "편의점",
        "title": "네이버페이 주말 혜택",
        "benefit_type": "적립",
        "discount_rate": 0.0,
        "conditions": "금·토·일 NPay 현장결제 2천원 이상",
        "valid_from": "2025-08-01",
        "valid_to": "2025-08-31",
        "source_url": "https://m.7-eleven.co.kr/product/eventList.asp",
        "is_active": True,
        "text": "주말 결제 시 포인트 적립."
    },
    {
        "id": "cu-202508-kakao-securities",
        "brand": "CU",
        "brand_aliases": ["씨유","PocketCU"],
        "category": "편의점",
        "title": "카카오페이증권 X CU",
        "benefit_type": "증정",
        "discount_rate": 0.0,
        "conditions": "행사상품 구매 후 CU포인트 적립",
        "valid_from": "2025-08-01",
        "valid_to": "2025-08-31",
        "source_url": "https://www.pocketcu.co.kr/event/main",
        "is_active": True,
        "text": "포인트 적립 고객에 주식 선물 제공."
    },
    {
        "id": "cu-202508-npay-soda-700",
        "brand": "CU",
        "brand_aliases": ["씨유","PocketCU","네이버플러스"],
        "category": "편의점",
        "title": "네이버페이 멤버십 특가",
        "benefit_type": "할인",
        "discount_rate": 0.0,
        "conditions": "네이버플러스 멤버십, NPay 결제 시 탄산음료 700원",
        "valid_from": "2025-08-01",
        "valid_to": "2025-08-31",
        "source_url": "https://www.pocketcu.co.kr/event/main",
        "is_active": True,
        "text": "멤버십 전용 탄산 특가."
    },
    {
        "id": "cu-202508-pocketcu-join",
        "brand": "CU",
        "brand_aliases": ["씨유","PocketCU"],
        "category": "편의점",
        "title": "포켓CU 멤버십 가입 혜택",
        "benefit_type": "할인",
        "discount_rate": 50.0,
        "conditions": "신규 가입자 CU알뜰택배 반값",
        "valid_from": "2025-08-01",
        "valid_to": "2025-08-31",
        "source_url": "https://www.pocketcu.co.kr/event/main",
        "is_active": True,
        "text": "가입 고객 택배 50% 할인."
    },

    # ==================== 마트 | 홈플러스 ====================
    {
        "id": "homeplus-202508-snacks-5000",
        "brand": "홈플러스",
        "brand_aliases": ["Homeplus"],
        "category": "마트",
        "title": "인기 과자&음료 5천원 할인",
        "benefit_type": "할인",
        "discount_rate": 0.0,
        "conditions": "2만원 이상 구매 시 5,000원",
        "valid_from": "2025-08-07",
        "valid_to": "2025-08-10",
        "source_url": "https://mfront.homeplus.co.kr/eventcoupon?tabType=ALL",
        "is_active": True,
        "text": "금액 조건 충족 시 즉시 할인."
    },
    {
        "id": "homeplus-202508-brand-10000",
        "brand": "홈플러스",
        "brand_aliases": ["Homeplus"],
        "category": "마트",
        "title": "인기 브랜드 1만원 할인",
        "benefit_type": "할인",
        "discount_rate": 0.0,
        "conditions": "3만원 이상 구매",
        "valid_from": "2025-08-08",
        "valid_to": "2025-08-10",
        "source_url": "https://mfront.homeplus.co.kr/eventcoupon?tabType=ALL",
        "is_active": True,
        "text": "3만원 이상 시 10,000원 할인."
    },
    {
        "id": "homeplus-202508-ramen-15",
        "brand": "홈플러스",
        "brand_aliases": ["Homeplus"],
        "category": "마트",
        "title": "인기 라면 15% 할인",
        "benefit_type": "할인",
        "discount_rate": 15.0,
        "conditions": "1.5만원 이상 구매, 최대 3천원",
        "valid_from": "2025-08-09",
        "valid_to": "2025-08-10",
        "source_url": "https://mfront.homeplus.co.kr/eventcoupon?tabType=ALL",
        "is_active": True,
        "text": "라면류 카테고리 할인."
    },
    {
        "id": "homeplus-202508-chickenbreast-15",
        "brand": "홈플러스",
        "brand_aliases": ["Homeplus"],
        "category": "마트",
        "title": "닭 가슴살 15% 할인",
        "benefit_type": "할인",
        "discount_rate": 15.0,
        "conditions": "쿠폰 발급일로부터 1일",
        "valid_from": "2025-08-08",
        "valid_to": "2025-08-10",
        "source_url": "https://mfront.homeplus.co.kr/eventcoupon?tabType=ALL",
        "is_active": True,
        "text": "단기 쿠폰형 할인."
    },
    {
        "id": "homeplus-202508-readymeal-25",
        "brand": "홈플러스",
        "brand_aliases": ["Homeplus"],
        "category": "마트",
        "title": "방학 간편식 25% 할인",
        "benefit_type": "할인",
        "discount_rate": 25.0,
        "conditions": "1.5만원 이상, 최대 5천원",
        "valid_from": "2025-08-08",
        "valid_to": "2025-08-10",
        "source_url": "https://mfront.homeplus.co.kr/eventcoupon?tabType=ALL",
        "is_active": True,
        "text": "간편식 카테고리 할인."
    },
    {
        "id": "homeplus-202508-necessities-5000",
        "brand": "홈플러스",
        "brand_aliases": ["Homeplus"],
        "category": "마트",
        "title": "생필품 1.5만 5천원 할인",
        "benefit_type": "할인",
        "discount_rate": 0.0,
        "conditions": "1.5만원 이상 구매 시 5천원",
        "valid_from": "2025-08-08",
        "valid_to": "2025-08-13",
        "source_url": "https://mfront.homeplus.co.kr/eventcoupon?tabType=ALL",
        "is_active": True,
        "text": "카테고리 즉시할인 쿠폰."
    },
    {
        "id": "homeplus-202508-tosspay-1000",
        "brand": "홈플러스",
        "brand_aliases": ["Homeplus","토스페이"],
        "category": "마트",
        "title": "토스페이 할인 쿠폰",
        "benefit_type": "할인",
        "discount_rate": 0.0,
        "conditions": "4만원 이상 구매 시 1,000원",
        "valid_from": "2025-08-01",
        "valid_to": "2025-08-31",
        "source_url": "https://mfront.homeplus.co.kr/eventcoupon?tabType=ALL",
        "is_active": True,
        "text": "결제수단 제휴 할인."
    },
    {
        "id": "homeplus-202508-npay-1000",
        "brand": "홈플러스",
        "brand_aliases": ["Homeplus","네이버페이"],
        "category": "마트",
        "title": "네이버페이 할인 쿠폰",
        "benefit_type": "할인",
        "discount_rate": 0.0,
        "conditions": "4만원 이상 구매 시 1,000원",
        "valid_from": "2025-08-01",
        "valid_to": "2025-08-31",
        "source_url": "https://mfront.homeplus.co.kr/eventcoupon?tabType=ALL",
        "is_active": True,
        "text": "NPay 결제 시 즉시할인."
    },

    # ==================== 마트 | 이마트 ====================
    {
        "id": "emart-202508-eel-abalone-50",
        "brand": "이마트",
        "brand_aliases": ["emart","SSG"],
        "category": "마트",
        "title": "민물장어·전복 50% 할인",
        "benefit_type": "할인",
        "discount_rate": 50.0,
        "conditions": "신세계포인트 적립 시",
        "valid_from": "2025-08-08",
        "valid_to": "2025-08-13",
        "source_url": "https://eapp.emart.com/news/event/progress_list_renew.do?eventTp=E",
        "is_active": True,
        "text": "포인트 적립 조건으로 반값."
    },
    {
        "id": "emart-202508-wine-50",
        "brand": "이마트",
        "brand_aliases": ["emart"],
        "category": "마트",
        "title": "와인 할인(브레이크 포인트 말보로 쇼비뇽 블랑)",
        "benefit_type": "할인",
        "discount_rate": 50.0,
        "conditions": "행사 기간 한정",
        "valid_from": "2025-08-08",
        "valid_to": "2025-08-13",
        "source_url": "https://eapp.emart.com/news/event/progress_list_renew.do?eventTp=E",
        "is_active": True,
        "text": "지정 와인 50% 할인."
    },
    {
        "id": "emart-202508-membership-5off",
        "brand": "이마트",
        "brand_aliases": ["emart","이마트몰"],
        "category": "마트",
        "title": "이달의 멤버십 할인쿠폰",
        "benefit_type": "할인",
        "discount_rate": 5.0,
        "conditions": "몰 전용 5만원 이상, 최대 3천원, 쿠폰 4장",
        "valid_from": "2025-08-01",
        "valid_to": "2025-08-31",
        "source_url": "https://eapp.emart.com/news/event/progress_list_renew.do?eventTp=E",
        "is_active": True,
        "text": "월간 멤버십 장바구니 할인."
    },
    {
        "id": "emart-202508-bithumb-join",
        "brand": "이마트",
        "brand_aliases": ["emart","빗썸"],
        "category": "마트",
        "title": "빗썸 제휴 이벤트",
        "benefit_type": "증정",
        "discount_rate": 0.0,
        "conditions": "빗썸 신규 가입 시 최대 95,000원 혜택",
        "valid_from": "2025-08-01",
        "valid_to": "2025-08-31",
        "source_url": "https://eapp.emart.com/news/event/progress_list_renew.do?eventTp=E",
        "is_active": True,
        "text": "신규 가입자 대상 제휴 리워드."
    },

    # ==================== 패션 ====================
    {
        "id": "musinsa-202508-pay-cards",
        "brand": "무신사",
        "brand_aliases": ["Musinsa"],
        "category": "패션",
        "title": "무신사페이 제휴카드 할인",
        "benefit_type": "할인",
        "discount_rate": 0.0,
        "conditions": "현대/롯데/삼성/하나카드 등 무신사페이 결제",
        "valid_from": "2025-08-01",
        "valid_to": "2025-08-31",
        "source_url": "https://www.musinsa.com/mz/community-event_notice",
        "is_active": True,
        "text": "제휴 카드 결제 시 할인 혜택."
    },
    {
        "id": "musinsa-202507-spa-festival",
        "brand": "무신사",
        "brand_aliases": ["Musinsa","SPA"],
        "category": "패션",
        "title": "SPA 브랜드 페스티벌",
        "benefit_type": "할인",
        "discount_rate": 80.0,
        "conditions": "인기 SPA 최대 80% 할인",
        "valid_from": "2025-07-07",
        "valid_to": "2025-08-17",
        "source_url": "https://www.musinsa.com/mz/community-event_notice",
        "is_active": True,
        "text": "20여 개 SPA 브랜드 특가."
    },
    {
        "id": "zigzag-202508-tech-festa",
        "brand": "지그재그",
        "brand_aliases": ["ZIGZAG"],
        "category": "패션",
        "title": "테크 페스타",
        "benefit_type": "할인",
        "discount_rate": 0.0,
        "conditions": "가전·디지털 연중 최대가 특가",
        "valid_from": "2025-08-04",
        "valid_to": "2025-08-17",
        "source_url": "https://zigzag.kr/events/e25f8ced-1b32-4536-ac6c-329e5a1e961d",
        "is_active": True,
        "text": "가전/디지털 기기 특가전."
    },
    {
        "id": "zigzag-202508-blackup-seasonoff",
        "brand": "지그재그",
        "brand_aliases": ["ZIGZAG","블랙업"],
        "category": "패션",
        "title": "블랙업 시즌오프",
        "benefit_type": "할인",
        "discount_rate": 70.0,
        "conditions": "쿠폰팩 제공 포함",
        "valid_from": "2025-08-07",
        "valid_to": "2025-08-10",
        "source_url": "https://zigzag.kr/events/e25f8ced-1b32-4536-ac6c-329e5a1e961d",
        "is_active": True,
        "text": "최대 70% 할인 + 쿠폰."
    },
    {
        "id": "zigzag-202508-water-items",
        "brand": "지그재그",
        "brand_aliases": ["ZIGZAG"],
        "category": "패션",
        "title": "물놀이템 특가",
        "benefit_type": "할인",
        "discount_rate": 0.0,
        "conditions": "스윔웨어·물놀이용품 특가",
        "valid_from": "2025-08-07",
        "valid_to": "2025-08-17",
        "source_url": "https://zigzag.kr/events/e25f8ced-1b32-4536-ac6c-329e5a1e961d",
        "is_active": True,
        "text": "여름 시즌 한정 특가."
    },
    {
        "id": "zigzag-202508-kakaopay-12",
        "brand": "지그재그",
        "brand_aliases": ["ZIGZAG","카카오페이"],
        "category": "패션",
        "title": "카카오페이 결제 할인",
        "benefit_type": "할인",
        "discount_rate": 12.0,
        "conditions": "최대 12% + 3,000원 추가",
        "valid_from": "2025-08-01",
        "valid_to": "2025-08-31",
        "source_url": "https://zigzag.kr/events/e25f8ced-1b32-4536-ac6c-329e5a1e961d",
        "is_active": True,
        "text": "결제 즉시 할인 및 추가 쿠폰."
    },
    {
        "id": "zigzag-202508-tosspay-3p5",
        "brand": "지그재그",
        "brand_aliases": ["ZIGZAG","토스페이"],
        "category": "패션",
        "title": "토스페이 결제 3.5% 할인",
        "benefit_type": "할인",
        "discount_rate": 3.5,
        "conditions": "결제 시 쿠폰 적용",
        "valid_from": "2025-08-01",
        "valid_to": "2025-08-31",
        "source_url": "https://zigzag.kr/events/e25f8ced-1b32-4536-ac6c-329e5a1e961d",
        "is_active": True,
        "text": "토스페이 전용 쿠폰."
    },
]

# 현재 날짜 기준 통계 출력
def print_date_statistics():
    current = datetime.now()
    active_count = 0
    expired_count = 0
    print(f"\n📊 날짜 기준 통계 (현재: {current.strftime('%Y-%m-%d')})")
    print("-" * 50)
    for item in MULTI_CATEGORY_DATA:
        valid_to = datetime.fromisoformat(item['valid_to'])
        status = "✅ 유효" if valid_to >= current else "❌ 만료"
        if status == "✅ 유효":
            active_count += 1
        else:
            expired_count += 1
        print(f"{item['brand']} | {item['title']} -> {item['valid_to']} {status}")
    print(f"\n총 {len(MULTI_CATEGORY_DATA)}개 중:")
    print(f"✅ 유효한 이벤트: {active_count}개")
    print(f"❌ 만료된 이벤트: {expired_count}개")
    print(f"📈 유효율: {active_count/len(MULTI_CATEGORY_DATA)*100:.1f}%")

if __name__ == "__main__":
    print_date_statistics()

